/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <NSSearchField.h>

@class NSString;

@interface WebSearchField : NSSearchField
{
    NSString *_searchTextToolTip;
    NSString *_cancelToolTip;
    NSString *_recentSearchesToolTip;
    NSString *_snapBackToolTip;
    long long _searchTextToolTipTag;
    long long _cancelToolTipTag;
    long long _recentSearchesToolTipTag;
    long long _snapBackToolTipTag;
    BOOL _toolTipRectanglesUpToDate;
    BOOL _inTextDidEndEditing;
    BOOL _becomingFirstResponder;
}

+ (void)initialize;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)snapBackCell;
- (void)setIsShowingSnapBack:(BOOL)arg1;
- (BOOL)isShowingSnapBack;
- (BOOL)performKeyEquivalent:(id)arg1;
- (BOOL)becomeFirstResponder;
- (void)selectText:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (void)setSearchTextToolTip:(id)arg1;
- (id)searchTextToolTip;
- (void)setCancelToolTip:(id)arg1;
- (id)cancelToolTip;
- (void)setSnapBackToolTip:(id)arg1;
- (id)snapBackToolTip;
- (void)setRecentSearchesToolTip:(id)arg1;
- (id)recentSearchesToolTip;
- (void)removeAllToolTips;
- (void)setFrameOrigin:(struct CGPoint)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (id)toolTip;
- (void)resetCursorRects;
- (id)view:(id)arg1 stringForToolTip:(long long)arg2 point:(struct CGPoint)arg3 userData:(void *)arg4;

@end

